/*import org.junit.Test;
import static org.junit.Assert.*;


 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'spadi2' at '10/25/16 2:49 PM' with Gradle 2.11
 *
 * @author spadi2, @date 10/25/16 2:49 PM
 
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
*/